package Com.Crm.Travel.common.enums;

public enum AppUserPermissions {
    // SALES
    QUERY_CREATE,
    QUERY_ASSIGN,
    QUERY_VIEW,
    QUOTE_CREATE,
    QUOTE_UPDATE,
    DEAL_CONFIRM,

    // OPERATIONS
    TRIP_CREATE,
    TRIP_ASSIGN,
    TICKET_UPLOAD,
    VISA_PROCESS,

    // ACCOUNTS
    EXPENSE_ADD,
    EXPENSE_VIEW,
    INVOICE_CREATE,
    LEDGER_VIEW,

    // ADMIN
    USER_CREATE,
    USER_MANAGE,
    PERMISSION_ASSIGN,
    SYSTEM_CONFIG
}
